2020-06-01 22:28:55,386 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 22:28:55,386 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 22:29:11,086 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-01 22:29:11,086 -- [base_page.py-->line:120] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-01 22:31:55,158 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='btn disable']")--失败
2020-06-01 22:31:55,158 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 22:33:01,294 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 22:33:01,295 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 22:33:08,870 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-01 22:33:08,871 -- [base_page.py-->line:93] - ERROR: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)

2020-06-01 22:39:24,837 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 22:39:24,838 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 22:39:33,354 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='btn disable']")--失败
2020-06-01 22:39:33,354 -- [base_page.py-->line:120] - ERROR: 'NoneType' object has no attribute 'click'
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
AttributeError: 'NoneType' object has no attribute 'click'
2020-06-01 23:05:00,672 -- [base_page.py-->line:32] - ERROR: 元素--('xpath', "//div[@id='show-tip']/span")--等待可见超时
2020-06-01 23:05:00,969 -- [base_page.py-->line:33] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-01 23:05:04,285 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 23:05:04,286 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:05:11,895 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-01 23:05:11,896 -- [base_page.py-->line:93] - ERROR: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:08:10,979 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//div[@class='padding-cont pt-login']//a[@class='btn-btn']")--失败
2020-06-01 23:08:10,980 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='padding-cont pt-login']//a[@class='btn-btn']"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='padding-cont pt-login']//a[@class='btn-btn']"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:08:13,494 -- [test_classOperation.py-->line:68] - ERROR: -------用例执行失败---case为：{'join_code': 'P69UVV', 'excepted': '加入课堂成功'}--------
2020-06-01 23:08:13,494 -- [test_classOperation.py-->line:69] - ERROR: assert 'P69UVV' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 66, in test_join_class
    assert case['join_code'] == res
AssertionError: assert 'P69UVV' == None
2020-06-01 23:08:55,298 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='btn disable']")--失败
2020-06-01 23:08:55,299 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:09:24,780 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//div[@class='padding-cont pt-login']//a[@class='btn-btn']")--失败
2020-06-01 23:09:24,780 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='padding-cont pt-login']//a[@class='btn-btn']"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='padding-cont pt-login']//a[@class='btn-btn']"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:15:31,860 -- [test_classOperation.py-->line:68] - ERROR: -------用例执行失败---case为：{'join_code': 'P69UVV', 'excepted': '加入课堂成功'}--------
2020-06-01 23:15:31,861 -- [test_classOperation.py-->line:69] - ERROR: assert 'P69UVV' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 66, in test_join_class
    assert case['join_code'] == res
AssertionError: assert 'P69UVV' == None
2020-06-01 23:15:48,860 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='btn disable']")--失败
2020-06-01 23:15:48,860 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:19:48,044 -- [test_classOperation.py-->line:68] - ERROR: -------用例执行失败---case为：{'join_code': 'P69UVV', 'excepted': '加入课堂成功'}--------
2020-06-01 23:19:48,044 -- [test_classOperation.py-->line:69] - ERROR: assert 'P69UVV' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 66, in test_join_class
    assert case['join_code'] == res
AssertionError: assert 'P69UVV' == None
2020-06-01 23:20:05,961 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='btn disable']")--失败
2020-06-01 23:20:05,961 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn disable']"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:24:10,693 -- [test_classOperation.py-->line:68] - ERROR: -------用例执行失败---case为：{'join_code': 'P69UVV', 'excepted': '加入课堂成功'}--------
2020-06-01 23:24:10,694 -- [test_classOperation.py-->line:69] - ERROR: assert 'P69UVV' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 66, in test_join_class
    assert case['join_code'] == res
AssertionError: assert 'P69UVV' == None
2020-06-01 23:28:48,408 -- [test_classOperation.py-->line:68] - ERROR: -------用例执行失败---case为：{'join_code': 'P69UVV', 'excepted': '加入课堂成功'}--------
2020-06-01 23:28:48,409 -- [test_classOperation.py-->line:69] - ERROR: assert 'P69UVV' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 66, in test_join_class
    assert case['join_code'] == res
AssertionError: assert 'P69UVV' == None
2020-06-01 23:31:58,303 -- [test_classOperation.py-->line:68] - ERROR: -------用例执行失败---case为：{'join_code': 'P69UVV', 'excepted': '加入课堂成功'}--------
2020-06-01 23:31:58,303 -- [test_classOperation.py-->line:69] - ERROR: assert 'P69UVV' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 66, in test_join_class
    assert case['join_code'] == res
AssertionError: assert 'P69UVV' == None
2020-06-01 23:32:42,225 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@id='show-tip']/span")--属性失败
2020-06-01 23:32:42,226 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:39:53,383 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 23:39:53,384 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:40:06,627 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-01 23:40:06,628 -- [base_page.py-->line:93] - ERROR: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:42:06,352 -- [base_page.py-->line:32] - ERROR: 元素--('xpath', "//div[@id='show-tip']/span")--等待可见超时
2020-06-01 23:42:06,352 -- [base_page.py-->line:33] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-01 23:45:30,564 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 23:45:30,565 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:45:46,176 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-01 23:45:46,176 -- [base_page.py-->line:120] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:45:50,624 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-01 23:45:50,624 -- [base_page.py-->line:93] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:55:16,323 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-01 23:55:16,323 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:55:32,068 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-01 23:55:32,068 -- [base_page.py-->line:120] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-01 23:55:47,882 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-01 23:55:47,883 -- [base_page.py-->line:93] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-02 00:00:30,964 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-02 00:00:30,964 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-02 00:00:42,502 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-02 00:00:42,502 -- [base_page.py-->line:93] - ERROR: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)

2020-06-02 00:03:09,717 -- [base_page.py-->line:32] - ERROR: 元素--('xpath', "//div[@id='show-tip']/span")--等待可见超时
2020-06-02 00:03:09,717 -- [base_page.py-->line:33] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-02 00:03:12,131 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-02 00:03:12,132 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-02 00:03:27,706 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-02 00:03:27,707 -- [base_page.py-->line:120] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-02 00:03:43,457 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-02 00:03:43,457 -- [base_page.py-->line:93] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)

2020-06-02 00:04:05,101 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-02 00:04:05,102 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:21:18,629 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@id='show-tip']/span")--属性失败
2020-06-02 07:21:18,666 -- [base_page.py-->line:134] - ERROR: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 130, in get_ele_attr
    attr_value = ele.get_attribute(attr_name)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 139, in get_attribute
    attributeValue = self.parent.execute_script(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:24:07,210 -- [test_classOperation.py-->line:89] - ERROR: -------用例执行失败---case为：{'pwd': '1981925d7', 'excepted': '课程退课成功'}--------
2020-06-02 07:24:07,211 -- [test_classOperation.py-->line:90] - ERROR: assert '课程退课成功' == '加入课堂成功'
  - 加入课堂成功
  + 课程退课成功
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classOperation.py", line 87, in test_quit_class
    assert case['excepted'] == res
AssertionError: assert '课程退课成功' == '加入课堂成功'
  - 加入课堂成功
  + 课程退课成功
2020-06-02 07:36:15,990 -- [base_page.py-->line:32] - ERROR: 元素--('xpath', "//div[@id='show-tip']/span")--等待可见超时
2020-06-02 07:36:15,990 -- [base_page.py-->line:33] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-02 07:36:31,746 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@id='error-tip']/span")--属性失败
2020-06-02 07:36:31,746 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='error-tip']/span"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\page_userinfo.py", line 59, in res_exit_class
    self.wait_ele_visibility(loc.show_tip, '用户页面---等待退课成功后显示提示框')
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 36, in wait_ele_visibility
    raise e
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='error-tip']/span"}
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:41:10,902 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@id='show-tip']/span")--属性失败
2020-06-02 07:41:10,902 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:41:26,594 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@id='error-tip']/span")--属性失败
2020-06-02 07:41:26,594 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='error-tip']/span"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\page_userinfo.py", line 61, in res_exit_class
    self.get_ele_attr(loc.show_tip, '用户页面---获取退课之后的回显', "innerText")
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 137, in get_ele_attr
    raise e
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='error-tip']/span"}
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:45:42,818 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-02 07:45:42,819 -- [base_page.py-->line:120] - ERROR: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (283, 431). Other element would receive the click: <div class="bg" style="display: block;"></div>
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:45:47,079 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-02 07:45:47,080 -- [base_page.py-->line:93] - ERROR: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)

2020-06-02 07:46:53,658 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@id='show-tip']/span")--属性失败
2020-06-02 07:46:53,659 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='show-tip']/span"}
  (Session info: chrome=83.0.4103.61)

2020-06-16 12:35:48,894 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='new-tj1']")--失败
2020-06-16 12:35:48,940 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='new-tj1']"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='new-tj1']"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:36:04,685 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@class='weui_dialog_bd']")--属性失败
2020-06-16 12:36:04,686 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='weui_dialog_bd']"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='weui_dialog_bd']"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:36:21,877 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 12:36:21,877 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:36:37,435 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-16 12:36:37,435 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:36:53,025 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-16 12:36:53,025 -- [base_page.py-->line:93] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='deletekccon']//input"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='deletekccon']//input"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:42:15,928 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[@class='new-tj1']")--失败
2020-06-16 12:42:15,928 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='new-tj1']"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='new-tj1']"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:42:31,501 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@class='weui_dialog_bd']")--属性失败
2020-06-16 12:42:31,502 -- [base_page.py-->line:134] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='weui_dialog_bd']"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='weui_dialog_bd']"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:42:48,154 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 12:42:48,154 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:43:03,648 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-16 12:43:03,649 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:43:15,670 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-16 12:43:15,670 -- [base_page.py-->line:93] - ERROR: 'NoneType' object has no attribute 'send_keys'
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
AttributeError: 'NoneType' object has no attribute 'send_keys'
2020-06-16 12:48:00,278 -- [base_page.py-->line:66] - ERROR: 元素--('xpath', "//a[@class='new-tj1']")--等待被加载超时
2020-06-16 12:48:00,278 -- [base_page.py-->line:67] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 63, in wait_ele_presence
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 12:48:17,041 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 12:48:17,041 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:48:32,641 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-16 12:48:32,642 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:48:48,304 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-16 12:48:48,304 -- [base_page.py-->line:93] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='deletekccon']//input"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='deletekccon']//input"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:56:38,540 -- [base_page.py-->line:66] - ERROR: 元素--('xpath', "//a[@class='new-tj2 hide2 active']")--等待被加载超时
2020-06-16 12:56:38,540 -- [base_page.py-->line:67] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 63, in wait_ele_presence
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 12:56:55,696 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 12:56:55,696 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:57:11,404 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-16 12:57:11,404 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 12:57:26,853 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-16 12:57:26,854 -- [base_page.py-->line:93] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='deletekccon']//input"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='deletekccon']//input"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 13:02:52,821 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//a[contains(text(),'更新提交')]")--失败
2020-06-16 13:02:52,822 -- [base_page.py-->line:120] - ERROR: Message: element not interactable
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.106)

2020-06-16 13:03:01,500 -- [test_classInfo.py-->line:56] - ERROR: -------用例执行失败---case为：{'filename': 'F:\\柠檬班资料\\web自动化\\ui_class_pai\\error_image\\用户页面---点击-班级下方更多按钮_1591051542.8233833.png', 'excepted': '作业提交成功'}--------
2020-06-16 13:03:01,501 -- [test_classInfo.py-->line:57] - ERROR: assert '作业提交成功' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classInfo.py", line 54, in test_upload_task
    assert case['excepted'] == res
AssertionError: assert '作业提交成功' == None
2020-06-16 13:03:11,169 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 13:03:11,169 -- [base_page.py-->line:120] - ERROR: 'NoneType' object has no attribute 'click'
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
AttributeError: 'NoneType' object has no attribute 'click'
2020-06-16 13:05:43,730 -- [base_page.py-->line:133] - ERROR: 获取元素--('xpath', "//div[@class='weui_dialog_bd']")--属性失败
2020-06-16 13:05:43,752 -- [base_page.py-->line:134] - ERROR: Alert Text: 还有文件处于上传中，是否要放弃上传
Message: unexpected alert open: {Alert text : 还有文件处于上传中，是否要放弃上传}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 129, in get_ele_attr
    ele = self.driver.find_element(*locator)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 还有文件处于上传中，是否要放弃上传
Message: unexpected alert open: {Alert text : 还有文件处于上传中，是否要放弃上传}
  (Session info: chrome=83.0.4103.106)

2020-06-16 13:06:00,858 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 13:06:00,859 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 13:07:19,570 -- [test_classInfo.py-->line:56] - ERROR: -------用例执行失败---case为：{'filename': 'F:\\柠檬班资料\\web自动化\\ui_class_pai\\error_image\\用户页面---点击-班级下方更多按钮_1591051542.8233833.png', 'excepted': '作业提交成功'}--------
2020-06-16 13:07:19,571 -- [test_classInfo.py-->line:57] - ERROR: assert '作业提交成功' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classInfo.py", line 54, in test_upload_task
    assert case['excepted'] == res
AssertionError: assert '作业提交成功' == None
2020-06-16 13:07:35,993 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//a[@class='kdmore']//span")--失败
2020-06-16 13:07:35,993 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//a[@class='kdmore']//span"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 13:07:51,584 -- [base_page.py-->line:119] - ERROR: 点击元素--('xpath', "//dt[@class='bgclass1']//li[@class='kdli3']//a")--失败
2020-06-16 13:07:51,584 -- [base_page.py-->line:120] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 117, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//dt[@class='bgclass1']//li[@class='kdli3']//a"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 13:07:54,501 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//div[@class='deletekccon']//input")--失败
2020-06-16 13:07:54,501 -- [base_page.py-->line:93] - ERROR: 'NoneType' object has no attribute 'send_keys'
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
AttributeError: 'NoneType' object has no attribute 'send_keys'
2020-06-16 13:09:06,720 -- [test_classInfo.py-->line:56] - ERROR: -------用例执行失败---case为：{'filename': 'F:\\柠檬班资料\\web自动化\\ui_class_pai\\error_image\\用户页面---点击-班级下方更多按钮_1591051542.8233833.png', 'excepted': '作业提交成功'}--------
2020-06-16 13:09:06,721 -- [test_classInfo.py-->line:57] - ERROR: assert '作业提交成功' == None
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\test_case\test_classInfo.py", line 54, in test_upload_task
    assert case['excepted'] == res
AssertionError: assert '作业提交成功' == None
2020-06-16 14:56:37,066 -- [base_page.py-->line:49] - ERROR: 元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--等待可点击超时
2020-06-16 14:56:37,066 -- [base_page.py-->line:50] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 46, in wait_ele_clickble
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 14:59:14,824 -- [base_page.py-->line:92] - ERROR: 输入文本--('xpath', "//input[@name='account']")--失败
2020-06-16 14:59:14,824 -- [base_page.py-->line:93] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='account']"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 89, in input_text
    self.driver.find_element(*locator).send_keys(input)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name='account']"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 15:05:10,933 -- [base_page.py-->line:32] - ERROR: 元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--等待可见超时
2020-06-16 15:05:10,933 -- [base_page.py-->line:33] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 15:12:29,840 -- [base_page.py-->line:32] - ERROR: 元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--等待可见超时
2020-06-16 15:12:29,840 -- [base_page.py-->line:33] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 29, in wait_ele_visibility
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 15:13:42,475 -- [base_page.py-->line:66] - ERROR: 元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--等待被加载超时
2020-06-16 15:13:42,475 -- [base_page.py-->line:67] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 63, in wait_ele_presence
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 15:23:01,568 -- [base_page.py-->line:49] - ERROR: 元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--等待可点击超时
2020-06-16 15:23:01,568 -- [base_page.py-->line:50] - ERROR: Message: 
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 46, in wait_ele_clickble
    ele = WebDriverWait(self.driver, timeout, poll_frequency).until(
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2020-06-16 15:25:16,605 -- [base_page.py-->line:121] - ERROR: 点击元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--失败
2020-06-16 15:25:16,605 -- [base_page.py-->line:122] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 119, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 15:26:32,124 -- [base_page.py-->line:121] - ERROR: 点击元素--('xpath', "//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label")--失败
2020-06-16 15:26:32,124 -- [base_page.py-->line:122] - ERROR: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label"}
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 119, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='rt_rt_1eatpru6ukl81u43lfgrig1i1r3']//label"}
  (Session info: chrome=83.0.4103.106)

2020-06-16 15:35:05,766 -- [base_page.py-->line:121] - ERROR: 点击元素--('xpath', "//a/div[contains(text(),'添加作业文件')]")--失败
2020-06-16 15:35:05,766 -- [base_page.py-->line:122] - ERROR: Message: element click intercepted: Element <div class="webuploader-pick">...</div> is not clickable at point (167, 413). Other element would receive the click: <label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label>
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 119, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="webuploader-pick">...</div> is not clickable at point (167, 413). Other element would receive the click: <label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label>
  (Session info: chrome=83.0.4103.106)

2020-06-16 15:37:24,821 -- [base_page.py-->line:121] - ERROR: 点击元素--('xpath', "//a/div[contains(text(),'添加作业文件')]")--失败
2020-06-16 15:37:24,821 -- [base_page.py-->line:122] - ERROR: Message: element click intercepted: Element <div class="webuploader-pick">...</div> is not clickable at point (167, 413). Other element would receive the click: <label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label>
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 119, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="webuploader-pick">...</div> is not clickable at point (167, 413). Other element would receive the click: <label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label>
  (Session info: chrome=83.0.4103.106)

2020-06-16 15:39:34,391 -- [base_page.py-->line:121] - ERROR: 点击元素--('xpath', "//a/div[contains(text(),'添加作业文件')]")--失败
2020-06-16 15:39:34,392 -- [base_page.py-->line:122] - ERROR: Message: element click intercepted: Element <div class="webuploader-pick">...</div> is not clickable at point (167, 413). Other element would receive the click: <label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label>
  (Session info: chrome=83.0.4103.106)
Traceback (most recent call last):
  File "F:\柠檬班资料\web自动化\ui_class_pai\page\base_page.py", line 119, in click_ele
    ele = self.driver.find_element(*locator).click()
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\坂上青云\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="webuploader-pick">...</div> is not clickable at point (167, 413). Other element would receive the click: <label style="opacity: 0; width: 100%; height: 100%; display: block; cursor: pointer; background: rgb(255, 255, 255);"></label>
  (Session info: chrome=83.0.4103.106)

